### ISSUE TITLE
Building up the list from from PBS Great American Reads

### ISSUE THREAD

**Issue by uogbuji** [zepheira/librarylink_collections#3]
@erimille & @informaticmonad have had several approaches to the [PBS Great American Reads](https://www.pbs.org/the-great-american-read/books/#/). Now that I'm involved this ticket starts largely with my own approach, and I hope we can roll in what all of us learned.

Work in progress is at https://github.com/zepheira/librarylink_collections/blob/alamw2019/lists/greatamericanread.json

See also: https://github.com/zepheira/librarylink_collections/blob/master/lists/harrypotter.json

**Comment by uogbuji** [comment]
I started with a scraper for the titles. The GAR page is stupid dynamic content from JS, so needs Chrome inspect to get the meat of it.

<img width="1142" alt="screen shot 2019-01-24 at 10 39 52 pm" src="https://user-images.githubusercontent.com/279982/51789665-86890780-2148-11e9-8d57-004a2258b1ac.png">

Copy the highlighted element & paste into `gar.html`.

Then:

```
microx --html --find-text Mockingbird --show-attrs “id,class” gar.html
html/body/div[@class=“gar-pagewrap”]/div[@class=“gar-book-list”]/a[@class=“gar-book-item”]/div[@class=“gar-book-item-inner”]/div[@class=“gar-book-title-author”]/div[@class=“gar-book-info”]
```

I need to check into why I didn't get the full path to the title alone, which has a trailing `/b`.

```
microx --html --expr ‘html/body/div[@class=“gar-pagewrap”]/div[@class=“gar-book-list”]/a[@class=“gar-book-item”]/div[@class=“gar-book-item-inner”]/div[@class=“gar-book-title-author”]/div[@class=“gar-book-info”]/b’ gar.html
```

With an update to get just the string value of the title, and to remove the "(series)" text in some titles.

```
microx --html --expr 'html/body/div[@class="gar-pagewrap"]/div[@class="gar-book-list"]/a[@class="gar-book-item"]/div[@class="gar-book-item-inner"]/div[@class="gar-book-title-author"]/div[@class="gar-book-info"]/b' --foreach "substring-before(., ' (Series)')" gar.html > gar-titles.txt
```

Now we have a list of GAR titles.

**Comment by uogbuji** [comment]
Next step is converting titles to groups of ISBNs. Considered [isbn.nu](https://isbn.nu/), [isbndb.com](https://isbndb.com/isbn-database) ($$), [Google Books API](https://developers.google.com/books/docs/v1/using#PerformingSearch) and LibraryThing but settled on OpenLibrary for combined low hassle & no cost.

See also: [Alternatives to Amazon API](https://bibwild.wordpress.com/2009/05/19/alternatives-to-amazon-api/) (2009) about cover images overall but also has resources for resolving titles

I [implemented liblink_title_report](https://github.com/uogbuji/Library.Link/commit/ea3edc79cc41e89c9f0bcfe68aac5509298d4147)

```
liblink_title_report --title-list gar-titles.txt > greatamericanread.json
```

Note: I implemented this to be gentle on the OpenLibrary service.

Gloria then did a lot of cleanup, especially culling of the spurious search results we get from OpenLibrary.

**Comment by informaticmonad** [comment]
Details on cleanup: Combined ISBNs for matching works, removed duplicate ISBNs, removed additional titles that weren't on the GAR list, fixed capitalization for some titles

**Comment by uogbuji** [comment]
As Gloria mentions my first pass at `liblink_title_report` did not cull duplicate ISBNs across group boundaries. Now it does.
